#best_config_

Graphical_interface: false
ShowTrajectory: false
Trajectory_length: 50
TimeBetweenFrames: 0.1
LoadModel: false
Path2Model: "/home/srv/navstik/flytOS/ros_flyt_TLD/models/my_face"
SavingFile: "/home/srv/navstik/flytOS/ros_flyt_TLD/models/my_face"
Tracking3D: false
queue_size : 100
